# Generated by Django 6.0.4 on 2026-04-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biopsychosocialprofile',
            name='is_generating',
            field=models.BooleanField(default=False),
        ),
    ]
