# Generated by Django 6.0.4 on 2026-04-24 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_biopsychosocialprofile_is_generating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[('student', 'Aluno/Usuário comum'), ('teacher', 'Professor')],
                default='student',
                help_text='Define se a conta é de aluno/usuário comum ou professor',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='biopsychosocialprofile',
            name='user',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='profile',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='biopsychosocialprofile',
            name='student_name',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Nome do aluno quando o perfil for gerenciado por um professor',
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name='biopsychosocialprofile',
            name='teacher',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='student_profiles',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name='biopsychosocialprofile',
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(user__isnull=False, teacher__isnull=True)
                    | models.Q(user__isnull=True, teacher__isnull=False)
                ),
                name='accounts_profile_user_xor_teacher',
            ),
        ),
    ]
