# Generated by Django 6.0.3 on 2026-03-13 15:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_rationale', models.TextField(help_text='Análise da IA sobre por que este conjunto de recursos foi escolhido.')),
                ('context_snapshot', models.JSONField(default=dict, help_text='Cópia dos dados do perfil no momento da geração (para histórico).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('items', models.ManyToManyField(related_name='sessions', to='catalog.resourceitem')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_sessions', to='accounts.biopsychosocialprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(help_text='Nota de 1 a 5 para este recurso específico.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('user_comment', models.TextField(blank=True, null=True)),
                ('applied_to_model', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.resourceitem')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='recommendations.recommendationsession')),
            ],
            options={
                'unique_together': {('session', 'resource')},
            },
        ),
    ]
