# Generated by Django 6.0.3 on 2026-03-20 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_resourceitem_category'),
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='applied_to_model',
        ),
        migrations.RemoveField(
            model_name='recommendationsession',
            name='items',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.recommendationsession'),
        ),
        migrations.AlterField(
            model_name='recommendationsession',
            name='ai_rationale',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recommendationsession',
            name='context_snapshot',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='RecommendedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_justification', models.TextField()),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.resourceitem')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_items', to='recommendations.recommendationsession')),
            ],
        ),
    ]
