# Generated by Django 6.0.3 on 2026-03-28 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('recommendations', '0002_alter_recommendationsession_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendationsession',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.biopsychosocialprofile'),
        ),
    ]
