# Generated by Django 6.0.4 on 2026-04-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_alter_recommendationsession_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedtechnology',
            name='ai_model',
            field=models.CharField(default='llama3', max_length=50),
        ),
    ]
