# Generated by Django 6.0.4 on 2026-04-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_generatedtechnology_ai_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedtechnology',
            name='video_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
