# Generated by Django 6.0.4 on 2026-04-17 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0005_generatedtechnology_video_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedtechnology',
            name='video_id',
        ),
    ]
