# Generated by Django 6.0.2 on 2026-04-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0006_remove_generatedtechnology_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedtechnology',
            name='recommendation_source',
            field=models.CharField(choices=[('unknown', 'Origem nao identificada'), ('json_reference', 'Base de referencia'), ('ai_suggested', 'Sugestao livre da IA')], default='unknown', max_length=20),
        ),
    ]
