# Generated by Django 6.0.3 on 2026-03-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('TA', 'Tecnologia Assistiva'), ('EP', 'Estratégia Pedagógica'), ('MDA', 'Material Didático Acessível'), ('MI', 'Metodologia Inclusiva')], max_length=3)),
                ('description', models.TextField(blank=True)),
                ('technical_requirements', models.JSONField(blank=True, default=dict, help_text="Ex: {'SO': 'Windows', 'RAM': '4GB'}")),
                ('metadata_tags', models.JSONField(blank=True, default=list, help_text="Armazena os perfis atendidos (ex: ['TEA', 'TDAH'])")),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'category'), name='unique_resource_per_category')],
            },
        ),
    ]
